### ISSUE TITLE
Synchronize hover effect with jsTree

### ISSUE THREAD

**Issue by jochenberger** [deitch/jstree-grid#183] opened 2016-10-13 07:32 UTC
http://jsfiddle.net/nr2osx5a/2/
If you hover over the nodes with the mouse, you can see that the animation is slightly off. That's because the jstree CSS adds an animation in https://github.com/vakata/jstree/blob/3.3.2/src/themes/main.less#L5. That `transition` rule is however not used by jstreegrid.
You could just add the same rule to jstree-grid (see commented CSS in the fiddle), but that would mean that you have to watch the jsTree css for changes.
You could also try to copy styles from `getComputedStyle(jsTreeAnchor)`, but that's probably going to be rather complicated and you'd still have to know which style properties to look for.
I'm not sure if and/or how this could be accomplished without changing jsTree's CSS.

**Comment by deitch** [comment] 2016-10-20 11:24
Are you referring to the fact that when you hover over a row, the grid cell becomes class `jstree-hovered` highlighted before the tree node, and when you leave, it loses it before?

It always bothered me, but never had time to look into it. I assumed it was some form of animation. Thanks for finding it!

But I don't get it. That line of CSS is only for `.jstree-wholerow`, which is not used unless the "wholkrow" plugin is used, which it is not in this case. Is the `animation` coming from elsewhere?

**Comment by jochenberger** [comment] 2016-10-20 11:43
Yes, the animation comes from the `transition` CSS rule. Look at the CSS in the fiddle. If you remove the comment from the `transition` rule, the animation works for the grid cells too. But adding this rule to `.jstree-grid-cell` opens up the same issues that I mentioned in #184. If @vakata should decide to change the jsTree theme (e.g. change the animation duration) you would have to change yours too.

**Comment by adamjimenez** [comment] 2016-10-20 11:48
I ended up overriding the jsTree CSS and implementing my own highlight effect.
https://jsfiddle.net/adamjimenez/x9wd6k3x/

**Comment by deitch** [comment] 2016-10-20 13:07
@jochenberger:

> If you remove the comment from the transition rule, the animation works for the grid cells too

I believe you (and I tried it :-) ). But I don't get *why*. The line you highlighted is for `.jstree-wholerow`, so shouldn't apply.

I agree, I do not want to implement the same precise css in jstreegrid, as it does expose us to changes (i.e. makes it brittle). On the other hand, if we knew *why*, we could do something like you suggested. I am fine with grabbing the css setting from the tree itself (well, mostly fine, would be better if it just worked without these hacks), but without understanding where it applies the animation, it is difficult to do.

**Comment by deitch** [comment] 2016-10-20 13:10
> I ended up overriding the jsTree CSS and implementing my own highlight effect.

It is cool, but, again, leaves us easily broken when something changes in jstree. Unless we implement a fully independent treegrid (or which I have zero time and interest... unless it is non-jquery, like a native Angular, Aurelia, Polymer or React component), we should override as little as possible.

**Comment by jochenberger** [comment] 2016-10-20 13:22
The CSS also applies the rule to .jstree-anchor` in line 4, that's the one that matches. :-)

**Comment by deitch** [comment] 2016-10-20 14:52
Doh! I looked at the highlighted line, saw that the previous line was `.jstree-anchor`, but somehow my eyes glossed right over the fact that it has no definitions, just a comma. Nice catch!

OK, let's see if this is an approach. 

1. Could we apply `.jstree-anchor` to the grid cells to adopt the styling?
2. Could we find the relevant `.jstree-anchor` and grab the right `animation` and apply it?

**Comment by jochenberger** [comment] 2016-10-21 12:58
Or 3: @vakata introduces a `.jstree-hover-animation` class that has just the transition rule and we use that. :-)
Otherwise I'd vote for 2.

**Comment by deitch** [comment] 2016-10-21 13:28
Oh, definitely I like your option 3 better. 

Short summary @vakata : we apply the `.jstree-hovered` class to any grid cells in the same row when  it is applied to a node in the tree. But because you use animation via `.jstree-anchor`, we miss it. And we definitely do *not* want to recreate the css rules because of DRY and because something will break when jstree changes..

What @jochenberger is suggesting is that instead of applying the animations to `.jstree-anchor`, which may be used for other things, create a class called `.jstree-hover-animation`, put the `animation` rules in there, and apply that class wherever you need the animation. That would allow us to just apply it as well.

Good modular css coding, I guess.

**Comment by vakata** [comment] 2016-10-23 13:40
I just added a `.jstree-animated` class - you should be able to use that, it only has the `transition` rule, which applies to `.jstree-wholerow` and `.jstree-anchor`

**Comment by deitch** [comment] 2016-10-23 13:45
Love it! Awesome @vakata. 

I assume it is just in the latest `master` now, but what version will it land in?

**Comment by deitch** [comment] 2016-10-23 13:54
Resolved in favour of #189

**Closed by deitch** 2016-10-23 13:54 UTC

**Comment by vakata** [comment] 2016-10-23 13:57
It is in master now, it will land in the next patch version, but I will hold that off until you confirm this will do the trick.

**Comment by deitch** [comment] 2016-10-23 14:10
You mean, other than my own idiocy in putting the `jstree-animation` class onto the headers instead of the grid cells themselves? Sigh.

Fixed that, and, yes, I can confirm it works. But @jochenberger raised the issue, so good for him to confirm as well.

**Comment by vakata** [comment] 2016-10-23 14:16
Great, thank you. I also added the `core.themes.ellipsis` option with a few helper functions, but I changed a few lines of his CSS, so I will wait for him to confirm that too, before I release the next patch version.

**Comment by deitch** [comment] 2016-10-23 14:18
So if `core.theme.ellipsis === true`, then it will show an ellipsis for overflow? And we can just check that for adding the css to the grid? I *do* like that.

@jochenberger do you want to update your PR for that?

**Comment by vakata** [comment] 2016-10-23 14:24
Yes, it is in the settings array, but having added the ability to change that at runtime - you may want to look out for those changes too (although I doubt changing this behavior at runtime will happen often). The methods dealing with ellipsis are: `show_ellipsis`, `hide_ellipsis` and `toggle_ellipsis`, which in turn set the internal variable `_data.core.themes.ellipsis`. I updated the original issue as well, so I guess it will be best to move the discussion there :)

**Comment by jochenberger** [comment] 2016-10-24 08:48
http://jsfiddle.net/nr2osx5a/4/ uses jsTree master and jstree-grid 3.5.28 and the hover effect works just fine. So yes, I guess this  does the trick (tm). ;-)

**Comment by deitch** [comment] 2016-10-25 05:08
> I updated the original issue as well, so I guess it will be best to move the discussion there :)

That sounds like a very good idea.

**Comment by deitch** [comment] 2016-10-25 05:09
@jochenberger wrote:

> So yes, I guess this does the trick (tm). ;-)

Guess we are good then.
