### ISSUE TITLE
Hiding tree nodes does not hide grid columns

### ISSUE THREAD

**Issue by PetzeltA** [deitch/jstree-grid#222] opened 2017-04-04 07:54 UTC
When you hide a tree node (API method hide_node) the columns are still visible and the layout is broken.

To fix this issue, the this.bind-Method has to be modified.
You need to bind at least the hide_node-event (better also the show_node-event).
The code should look like this:

```js
      .on("show_node.jstree", $.proxy(function (e, data) {
      }, this))
      .on("hide_node.jstree", $.proxy(function (e, data) {
        var id = data.node.id;
        findDataCell(this.uniq, id, this._gridSettings.gridcols).remove();
        this._hide_grid(data.node);
      }, this))
```
Regards
Alex

**Comment by deitch** [comment] 2017-04-09 09:01
Thanks @PetzeltA . I am not sure I get the issue. Do you mean by clicking on the triangle, or using the API call? Perhaps a fiddle with the problem example?

In any case, with the proposed solution in hand (thank you, indeed), convert this to a PR?

**Comment by PetzeltA** [comment] 2017-04-09 11:20
I mean the API call hide_node.
To convert this into a PR would be helpful.
Last but not least: Here is a Fiddle: https://jsfiddle.net/qwnuaLm1/1/

**Comment by deitch** [comment] 2017-04-09 12:22
> Here is a Fiddle: https://jsfiddle.net/qwnuaLm1/1/

Cool, it shows the error. :-)

**Comment by deitch** [comment] 2017-04-09 12:38
@PetzeltA your code doesn't work. It catches the event, but as soon as it is done hiding them, they reappear at the bottom of the list?

**Comment by deitch** [comment] 2017-04-09 12:47
Not quite. It succeeds for each invocation of `$("div#jstree").jstree().hide_node(some_node);`, but each subsequent ruins it...

**Comment by PetzeltA** [comment] 2017-04-09 13:03
Hmm... I just tested by hiding 2 nodes that had a parent/child relation. :-(
So maybe if (this.is_hidden(obj)) { return };  in _prepare_grid could help?

**Comment by deitch** [comment] 2017-04-09 13:07
No, it seems to have something to do with `this.holdingCells`. At some point it is finding them later, for reasons I don't get.

**Comment by deitch** [comment] 2017-04-09 13:24
Hmm, calling `hide_node()` calls `redraw_node()` on that node and all of its peers and parent (which makes sense, since jstree needs to figure out what changes when you hide that).

The order it goes in is:

1. You call `hide_node()`
2. jstree calls `redraw_node()` for each node (except for the hidden one of course) and the immediate parent. This causes every cell to be redrawn, including the ones to be hidden.
3. jstree emits `hide_node` event.
4. jstree grid catches the `hide_node` event, and hides the single node intended to be hidden.

The problem is in the second stage. When it redraws the parent, it has all of the previously drawn cells in `this.holdingCells` and redraws them. This makes them all appear with every redraw, and thus only the most recent one hidden gets, well, hidden.

To be clear, it is the redraw on the *parent* that causes it. What we really need is a way to clear the `holdingCells` hash, which is used to hold stuff that hasn't yet been placed when drawing.

**Comment by deitch** [comment] 2017-04-09 13:28
Ah, it was the delete! `holdingCells` is supposed to be a stack-like cache. Once you get something from it, it should be deleted. Once that is reenabled, it works a charm. Merging in...

**Comment by deitch** [comment] 2017-04-09 13:31
Closed in favour of #223

**Closed by deitch** 2017-04-09 13:31 UTC

**Comment by deitch** [comment] 2017-04-09 13:33
And published.

**Comment by PetzeltA** [comment] 2017-04-10 04:54
Cool! :-)
