### ISSUE TITLE
Adding nodes sometimes breaks the layout

### ISSUE THREAD

**Issue by PetzeltA** [deitch/jstree-grid#224] opened 2017-04-11 07:12 UTC
Hi!
The fix you made last weekend lead to a new issue.
Now if we add a node the layout is broken again.

I've updated the Fiddle: https://jsfiddle.net/qwnuaLm1/2/

Regards
Alex

**Comment by deitch** [comment] 2017-04-12 05:26
Ah, I knew there was a reason we had that there. :-)

That is some expensive `NewProduct`!!

**Comment by PetzeltA** [comment] 2017-04-14 14:17
OK - I think this is the solution:
getHoldingCells has to be changed like this:

this.getHoldingCells = function (obj,col,hc) {
	var ret = $(), children = obj.children||[], child, i, uniq = this.uniq;
	// run through each child, render it, and then render its children recursively
	for (i=0;i<children.length;i++) {
		if (this.is_hidden(children[i])) { continue; }
		child = generateCellId(uniq,children[i])+col;
		if (hc[child] && obj.state.opened) {
			ret = ret.add(hc[child]).add(this.getHoldingCells(this.get_node(children[i]),col,hc));
		}
	}
	return(ret);
};

So if a child is hidden we don't have do redraw it's columns.
Thats all. :-)

**Comment by deitch** [comment] 2017-04-19 06:16
I renamed it `popHoldingCells()`. The problem is partially that once it gets the node from the `holdingCells`, it shouldn't stay there. The fact that it was remaining was part of the issue. So in the last commit, I renamed it `popHoldingCells` to indicate to all our future selves what it is supposed to do.

However, in popping it - which includes removing it from the stack via `delete hc[child]`, something else broke. I think your fix will work (thank you), but will double-check.

**Comment by deitch** [comment] 2017-04-19 07:28
So, your solution _would_ work, but only for a subset of cases. The problem has to do with rendering the `Products` node again. When it is done, it pops off its children and adds them right after it. When popping, it finds the Price column cells of the three children of `Products` - `Fruit`, `Vegetables`, `j1_16` (a.k.a. `NewProduct`) - and pushes them to just beneath it, shoving everything else down.

The questions then are:

1. Why is `NewProduct` showing up as empty in that set of three? This is a secondary, but good to know.
2. Why is the ordering messed up? It should render them correctly. Could have to do with popping them off the `holdingCells` stack vs getting them when they are deleted?

**Comment by PetzeltA** [comment] 2017-04-19 07:42
Can you provide a fiddle of a case that does not work?

**Comment by deitch** [comment] 2017-04-19 07:49
Not yet. I am still working through the logic. It may turn out that your solution _does_ work. 

FYI, this sorting and rendering of the cells is, by far, the hardest part of the grid. The grid used to be `span` elements inside the tree, but it became a positioning nightmare, so much so that we switched to a true grid. Pros and cons for both....

**Comment by deitch** [comment] 2017-04-19 08:17
When a node is rendered from `holdingCells`, it also renders all of its children. Earlier, it assumed that those children were also in `holdingCells`. However, that caused a lingering effect under certain circumstances, the issue you raised earlier.

The correct solution was to pop the node from the holding cell when it is rendered. However, that created this new issue: when rendering children recursively, the children no longer are guaranteed to be in `holdingCells`. 

The branch https://github.com/deitch/jstree-grid/tree/fix-add-child-issue addresses the issue. PR will be open soon, need to rerun tests.

**Comment by deitch** [comment] 2017-04-19 08:19
Ah, like a charm!

Closing in favour of https://github.com/deitch/jstree-grid/pull/227

**Closed by deitch** 2017-04-19 08:19 UTC
