### ISSUE TITLE
highlight column header on hover / click

### ISSUE THREAD

**Issue by adamjimenez** [deitch/jstree-grid#156] opened 2016-05-09 18:00 UTC
highlight the column headers when hovered or clicked

**Comment by deitch** [comment] 2016-05-11 05:14
Let's say we have a tree grid of 3 columns and 4 rows (in addition to the header). 

#### Hover

If I hover over C2 (3rd column, 2nd row), right now all of row 2 will be highlighted. Do you also want the header for C to be highlighted? Or do you mean the entire C column (header and all cells)? And if I slide left to hover over B2 (2nd column, 2nd row), then C header should be de-highlighted and B header (and possibly cells) should be highlighted?

#### Click

If I click on C2, right now all of row 2 is marked as clicked. Do you also want the C header (and possibly all C cells) to be marked as clicked? 

#### Summary

Are we essentially looking for Excel-like behaviour, where every cell that is highlighted or clicked shows the entire row and column?

**Comment by adamjimenez** [comment] 2016-05-11 05:26
I'm thinking about highlighting the header cell, not the entire column.

**Comment by deitch** [comment] 2016-05-11 07:07
That is pretty easy. I will show you a sample.

**Comment by deitch** [comment] 2016-05-11 07:25
Heh heh, you know what the problem is? The default background colour for the header cells is *identical* to the background colour of a hovered cell. So I add `jstree-hovered` to the header cell.... but you don't see the difference! Any suggestions?

**Comment by deitch** [comment] 2016-05-11 07:26
It actually works nicely. I have a separate branch and will put in a PR. But the colouring is a bit of an issue.

**Comment by adamjimenez** [comment] 2016-05-11 12:43
Different default bg? As long as it's adding the classes it's easy to override the colours. Put up a PR and I'll have a look.

**Comment by deitch** [comment] 2016-05-11 12:50
I changed the background slightly. PR.

**Closed** 2016-05-12 08:09 UTC
